### ISSUE TITLE
Toujours laisser une ligne vide avant une liste à puce

### ISSUE THREAD

**Issue by adogor** [Zenika/odp-to-md#19]
```
TEXTE
[LIGNE VIDE]
- PUCE
```

**Comment by ggerbaud** [comment]
Je suis d'accord mais il faudrait vérifier qu'il n'y a pas déjà une ligne vide et ne pas ajouter systématiquement une ligne vide au commencement d'une liste
De même attention aux sous-listes

**Comment by adogor** [comment]
https://github.com/adogor/odp-to-md/commit/5923c3bfee410e732198f46abec48aae6c8d4a0a
