### ISSUE TITLE
Multiple problems with Ubuntu

### ISSUE THREAD

**Issue by jaubin** [Zenika/odp-to-md#25]
Hello, 

The following problems appear with Ubuntu 14.04.2 LTS : 
- The nodejs executable is named nodejs and not node (which actually points to another package)
- npm must be run with sudo rights otherwise it won't work
- There's no way to make npm register the scripts (unless I don't know how to do it) so I have to write the command lines with absolute paths to the JS scripts

Rgds

**Comment by ldez** [comment]
- I recommend to you to follow Node documentation for install on Ubuntu. https://nodejs.org/en/download/package-manager/#debian-and-ubuntu-based-linux-distributions
- It's a problem with NPM
- same reason as NPM install
