### ISSUE TITLE
Le script devraient prendre plusieurs fichier odp en entrée

### ISSUE THREAD

**Issue by ggerbaud** [Zenika/odp-to-md#7]
Et ainsi générer le fichier slides.json

**Comment by adogor** [comment]
Ou un répertoire

**Comment by ggerbaud** [comment]
Tout à fait ;)
mais ce serait de pouvoir migrer toute la formation d'un coup

**Comment by sebbrousse** [comment]
un répertoire c'est :-1 pour moi
Trop de gestion pour pas grand chose, dans la plupart des outils on donne
la liste des fichiers.
Par contre, si on met plusieurs fichiers, il faut pouvoir générer plusieurs
fichiers ;)

2015-01-15 12:01 GMT+01:00 adogor notifications@github.com:

**Comment by ggerbaud** [comment]
pour moi un rep c'est pas déconnant avec une option -d et si on filtre ensuite sur les odp sans faire de récursif

et oui il faut créer autant de fichier en sortie qu'il y en a en entrée (et avec le bon nom, cf autre issue)
